//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class etudiant
    {
        public int id_etudiant { get; set; }
        public string nom_etudiant { get; set; }
        public string prenom_etudiant { get; set; }
        public string formation_A { get; set; }
        public string formation_B { get; set; }
        public string formation_C { get; set; }
        public Nullable<int> id_classe { get; set; }
    
        public virtual classe classe { get; set; }
    }
}
